libtref: tref::DecodedBitmap Class Reference
tref::DecodedBitmap Class Reference
libtref
Simple bitmap class used for output.
Public Member Functions
DecodedBitmap (std::byte *data, unsigned int width, unsigned int height) noexcept
Constructs a bitmap from existing data.
~DecodedBitmap () noexcept
Deallocates the bitmap.
std::span< const std::byte > data () const noexcept
Gets the bitmap's data.
unsigned int height () const noexcept
Gets the bitmap's height.
unsigned int width () const noexcept
Gets the bitmap's width.
Detailed Description
Simple bitmap class used for output.
Constructor & Destructor Documentation
DecodedBitmap()
tref::DecodedBitmap::DecodedBitmap (std::byte * data, unsigned int width, unsigned int height) noexcept
Constructs a bitmap from existing data.
Parameters
data The bitmap data.
width The bitmap width.
height The bitmap height.
~DecodedBitmap()
tref::DecodedBitmap::~DecodedBitmap () noexcept
Deallocates the bitmap.
Member Function Documentation
data()
std::span< const std::byte > tref::DecodedBitmap::data () const noexcept
Gets the bitmap's data.
Returns
The bitmap's data. The data is encoded in 32bbp RGBA format.
Referenced by DecodedBitmap(), and data().
height()
unsigned int tref::DecodedBitmap::height () const noexcept
Gets the bitmap's height.
Returns
The bitmap's height.
Referenced by DecodedBitmap(), and height().
width()
unsigned int tref::DecodedBitmap::width () const noexcept
Gets the bitmap's width.
Returns
The bitmap's width.
Referenced by DecodedBitmap(), and width().